apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ci-cd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ci-cd-app
  template:
    metadata:
      labels:
        app: my-ci-cd-app
    spec:
      containers:
      - name: my-ci-cd-app
        image: 735873741347.dkr.ecr.us-west-1.amazonaws.com/cicdpipeline:22
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
