apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: argocd
spec:
  type: ClusterIP
  selector:
    app: my-ci-cd-app
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
